### ISSUE TITLE
A few things from the first use

### ISSUE THREAD

**Issue by JustinBeardsley** [dphaener/fermentable-issues#4]
Here are a few things I noticed right off the bat, I'm sure the grain database is coming along and just takes time, same with the hops.

Grain Database is small, would like a way to manually enter grain names and data.  Also, there is some variance in the malts that relate to efficiency,  being able to customize a grain to reflect these changes as we get new lots from our suppliers would be helpful.

In hops, only can add one hop for each time, on subsequent hop additions the 'add hop' button does not respond if multiple hops for same addition time.  I can change the time once the hop is added.

Would also like to be able to enter hops manually.

Would like measurements in SG and bbl available.  User selectable in settings for quantities would be a nice option.

Dropdown  for adding new brew log does not populate with recipe.
-Justin

**Comment by JustinBeardsley** [comment]
And after reading the first issue, I have successfully activated the recipe, so scratch the last note.

**Comment by dphaener** [comment]
Ok great. I'll add the unit settings as a feature request. I'm actually building out the settings pages right now, so I'll just add that to the list.

I've received some requests to allow additions to the grain and hop database, which I have been hesitant to do. I think I'm going to implement it by adding user specific additions. I.E. any grains or hops you add to the database, will only be visible by you. I don't think I want that portion of the database to get too cluttered. I'd like to maintain some form of control over it.

Re hop addition bug. I have located the error and am working to fix it.

**Comment by JustinBeardsley** [comment]
Cool.  The grain thing could get very messy if everyone had the ability to add it to the global database, so I think its a good idea to have some user specific options.

**Comment by dphaener** [comment]
Fixed hop addition modal.

**Comment by dphaener** [comment]
@JustinBeardsley I'm implementing the feature you requested for adding your own hops and grain. For the grains I'm curious what exactly you're looking for. All I'm using for extract calculation is extract fine grind. Does it make sense to you to include anything else? Are you using anything else in your calculations, and if so, can I see the formula you're using?

**Comment by JustinBeardsley** [comment]
I average the FG and CG, so the top of the equation looks like this ((DBFG+DBCG)/2).  I just tied to make a new recipe, everything is working well, the extract potential is a little higher than what I see here, but that is likely due to only using the fine grind extract potential.  I did run into a problem, I was unable to activate the new recipe, I can click where it says "disabled" and the activate balloon shows up, but there is nothing clickable about it.   I tried the other recipe and it can activate and deactivate just fine.  So I modified the original recipe to the new recipe to try and get further.  When I went to create a batch log, an error happened, and I couldn't move forward.  It said it generated an error in the log, so you should be able to see it.  Otherwise, I like the new additions.

**Comment by dphaener** [comment]
Hmmm. As far as the recipe not being able to activate, it's because you don't have all of the ingredients in inventory. Looks like you're missing the Saaz. 

The fine grind and coarse grind thing....I could possibly integrate that, but a lot of grains do not include the analysis for coarse grind by default. One thing you can do to adjust the extract potential is tinker with the brewhouse efficiency. That factors into the extract calculation.

I am seeing all the errors and am looking into it right now.

**Comment by dphaener** [comment]
@JustinBeardsley Ok, I think I tracked down this issue. This is a strange one. What happened I believe, is that when you changed all the ingredients in an already active recipe, to include ingredients that weren't yet in inventory, the system choked when trying to create a batch. I don't let you activate a recipe and create a batch from it until you have everything in inventory, for several reasons. I didn't foresee someone doing this. :) I think I've figured out a fix for this, and will push it out shortly.

**Comment by JustinBeardsley** [comment]
That makes sense.

**Comment by dphaener** [comment]
@JustinBeardsley Ok it's fixed. Just had to trigger a callback after a recipe is updated and disable it if anything that was changed caused it to become unactivatable(is that even a word?). So, currently that recipe is still active, but if you change anything in the settings it will become disabled. Similarly, if you disable it, it won't be activatable until you fix the inventory issue.
