### ISSUE TITLE
Save less aggressively when editing or creating recipes

### ISSUE THREAD

**Issue by jleonar** [dphaener/fermentable-issues#7]
When using the UI to change or create a recipe, click the up or down arrows on amounts is interrupted by the automated saving.  Therefore, you can't click up or down repeatedly.

**Comment by jleonar** [comment]
Disregard, I didn't realize the field was editable by typing.

**Comment by dphaener** [comment]
:+1: there's actually a 300 millisecond delay delay between the time the arrow was last clicked and when the auto save is triggered. Deciding on 300ms was based on some testing but was mostly arbitrary. Reopening to keep it in my head just in case someone else brings it up.
