### ISSUE TITLE
Button Unresponsive on Half Screen Layout Chrome

### ISSUE THREAD

**Issue by NighthawkBrewery** [dphaener/fermentable-issues#9]
If I have Chrome using half of my screen space (native 1680x1050) the Recipes button will become mostly unclickable. Seems the "hitbox" or whatever it is for it is shrunk to only a few pixels thick line dividing the Recipes button and the Brew Logs button. All of the other buttons are unaffected.

**Comment by dphaener** [comment]
This was due to a layout issue on reduced width screens. I've deployed a fix, along with some other fluid layout fixes.
